### ISSUE TITLE
Movimentação do Player II

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#24]
# Descrição
### Sendo elas:

- Movimentação do player
- Movimentação da câmera
- Dash

# Referencias
## -

# Tasks

- [ ] Sistema de Pulo (Melhoria)
- [ ] Implementar as animacoes
- [ ] Trocar a camera pra cinemachine
- [ ] Melhorar o dash
