### ISSUE TITLE
Animações das Skills

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#30]
# Descrição
## Todas as animações das skills (6 iniciais)

# Referencias
## [GDD](https://www.canva.com/design/DAFbnGKaHOw/RkEvLyhFUpMgglFu3D0jWw/edit)

# Tasks

- [ ] Animação de Skill - Skill 1
- [ ] Animação de Skill - Skill 2
- [ ] Animação de Skill - Skill 3
- [ ] Animação de Skill - Skill 4
- [ ] Animação de Skill - Skill 5
- [ ] Animação de Skill - Skill 6
